### PR TITLE
Improve fetch-plus-json

### PR DESCRIPTION
**Pull request by mehcode**
- Return the whole response object and just overwrite the body property
- Resolve with null if status is 204 and JSON parse failed

### CODE REVIEW

**Comment by RickWong** [comment]
Thanks again.

I could immediately merge the first commit (204 and failure handling) however the second one is a "major" change to how this middleware works.

The thing is, I do not want to break this package for existing users who expect and/or prefer the current behavior. Would you agree that this new behavior deserves its own new middleware package like `fetch-plus-resolve-json`?

**Comment by mehcode** [comment]
@RickWong How about we add a configuration option to: https://github.com/RickWong/fetch-plus/blob/master/packages/fetch-plus-json/src/index.js#L18

Something like 

```
client.useMiddleware(fetchJson({simple: false});
```

And default `simple` to `true` (to maintain existing behavior). I'm not sold on the property name `simple` though.

**Comment by RickWong** [comment]
That's a good idea. The default behavior should be the old behavior, so maybe the flag should be named `wholeResponse: true` ?

**Comment by mehcode** [comment]
@RickWong Done.

**Comment by mehcode** [comment]
@RickWong Why do you export the `before` and `after` of the middleware? I did break the API of the `after` function. I'd consider that internal though so it shouldn't matter.

**Pull request merged**
